In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({
        'x1': range(4),
        'x2': range(1, 5),
        'y': range(2, 6),
    })

In [4]:
df

x1  x2  y
0   0   1  2
1   1   2  3
2   2   3  4
3   3   4  5

这是向量

In [5]:
df.x1.values.shape

(4,)

In [6]:
np.dot(df.x1.values, df.x2.values)

20

这是矩阵

In [7]:
df.loc[:, 'x1 x2'.split()].values

array([[0, 1],
       [1, 2],
       [2, 3],
       [3, 4]])

In [8]:
mt1 = df.loc[:, 'x1 x2'.split()].values

这里我定义一个隐层 3 个节点，用 numpy 表示出一个矩阵很方便

In [9]:
w1 = np.arange(1, 7).reshape((2, 3))

In [10]:
w1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
mt1

array([[0, 1],
       [1, 2],
       [2, 3],
       [3, 4]])

从输入层到隐层，矩阵相乘得到 a

In [13]:
a = np.dot(mt1, w1)

从隐层到输出层，这时有 3 个权重，一个输出，可以用 w2 来表示

In [14]:
w2 = np.arange(1, 4).reshape((3, 1))

In [15]:
w2

array([[1],
       [2],
       [3]])

In [16]:
a

array([[ 4,  5,  6],
       [ 9, 12, 15],
       [14, 19, 24],
       [19, 26, 33]])

In [17]:
y = np.dot(a, w2)

In [18]:
y

array([[ 32],
       [ 78],
       [124],
       [170]])

看完这个例子，有没觉得神经网络用矩阵表示非常优雅呢？